import type { Load } from "../ammo";
import { fitCurve, type MvCurve } from "../mv-curve";
import { G9, BBTI_9 } from "./shared";

// Ballistics by the Inch 2008: one barrel cut down an inch at a time. These also give the shape for similar loads.
const BBTI_115: MvCurve = [[4, 1094], [5, 1166], [6, 1188], [8, 1234], [10, 1253], [12, 1282], [14, 1295], [16, 1295], [18, 1297]]; // Federal 115 gr JHP
const BBTI_124: MvCurve = [[4, 1061], [5, 1115], [6, 1131], [8, 1180], [10, 1211], [12, 1225], [14, 1241], [16, 1243]]; // Federal 124 gr Hydra-Shok
const BBTI_147: MvCurve = [[4, 951], [5, 1007], [6, 1030], [8, 1047], [10, 1067], [12, 1081], [14, 1085], [16, 1085], [18, 1085]]; // Federal 147 gr Hydra-Shok

export const LOADS_9MM: Load[] = [
  {
    id: "9mm-115",
    group: G9,
    name: "115 gr FMJ",
    short: "9mm 115 gr FMJ",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.14,
    dragModel: "G1",
    mvByBarrel: BBTI_115,
    platform: "ar15",
    confidence: "medium",
    notes: "Curve measured with Federal 115 gr JHP; FMJ may run 50-90 fps faster. Chronograph your load: 9mm offsets are sensitive to velocity.",
    sources: [BBTI_9, { label: "Federal AE9DP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9DP.html" }],
  },
  {
    id: "9mm-124",
    group: G9,
    name: "124 gr FMJ / JHP",
    short: "9mm 124 gr",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.145,
    dragModel: "G1",
    mvByBarrel: BBTI_124,
    platform: "ar15",
    confidence: "medium",
    notes: "Curve measured with Federal 124 gr Hydra-Shok; flat past about 14 in.",
    sources: [BBTI_9, { label: "Federal AE9AP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9AP.html" }],
  },
  {
    id: "9mm-147",
    group: G9,
    name: "147 gr subsonic",
    short: "9mm 147 gr subsonic",
    weightGr: 147,
    diameterIn: 0.355,
    bc: 0.212,
    dragModel: "G1",
    mvByBarrel: BBTI_147,
    platform: "ar15",
    confidence: "medium",
    notes: "Curve measured with Federal 147 gr Hydra-Shok; flat at about 1,070-1,090 fps past 12 in.",
    sources: [BBTI_9, { label: "Federal AE9FP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9FP.html" }],
  },
  {
    id: "cci-blazer-9-115",
    group: G9,
    brand: "CCI",
    name: "CCI Blazer Brass 115 gr FMJ",
    sku: ["5200", "5239A"],
    short: "9mm Blazer Brass 115",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.152,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[3.39, 1050], [3.7, 1106], [4, 1104], [4.5, 1150], [5.3, 1156], [16, 1310]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 6 barrel lengths from 3.39 to 16 in (Pew Pew Tactical, AmmoLand); other lengths follow the Ballistics by the Inch 115 gr curve. Maker's rating: 1,145 fps from a 4 in test barrel. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "CCI 5200", url: "https://www.cci-ammunition.com/handgun/blazer/blazer-brass/6-5200.html" },
    ],
  },
  {
    id: "cci-blazer-9-124",
    group: G9,
    brand: "CCI",
    name: "CCI Blazer Brass 124 gr FMJ",
    sku: ["5201"],
    short: "9mm Blazer Brass 124",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.167,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.7, 1058], [4.5, 1088], [16, 1262]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 3.7, 4.5 and 16 in (Pew Pew Tactical); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,090 fps from a 4 in test barrel. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "CCI 5201", url: "https://www.cci-ammunition.com/handgun/blazer/blazer-brass/6-5201.html" },
    ],
  },
  {
    id: "fed-ae9dp",
    group: G9,
    brand: "Federal",
    name: "Federal American Eagle 115 gr FMJ",
    sku: ["AE9DP"],
    short: "9mm AE 115 FMJ",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.121,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[3.39, 1026], [4, 1146], [5.3, 1206]]),
    platform: "ar15",
    confidence: "low",
    notes: "Measured at 3.39, 4 and 5.3 in (AmmoLand); other lengths follow the Ballistics by the Inch 115 gr curve. Maker's rating: 1,180 fps from a 4 in test barrel. Only pistol barrels were measured, so carbine velocities are less certain. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "Federal AE9DP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9DP.html" },
    ],
  },
  {
    id: "fed-ae9ap",
    group: G9,
    brand: "Federal",
    name: "Federal American Eagle 124 gr FMJ",
    sku: ["AE9AP"],
    short: "9mm AE 124 FMJ",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.152,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[4, 1150]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,150 fps, 4 in test barrel); other lengths follow the Ballistics by the Inch 124 gr curve. Factory ratings often run fast, so a chronograph value is better. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Federal AE9AP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9AP.html" },
    ],
  },
  {
    id: "fed-ae9fp",
    group: G9,
    brand: "Federal",
    name: "Federal American Eagle 147 gr FMJ FP (subsonic)",
    sku: ["AE9FP"],
    short: "9mm AE 147 FMJ",
    sameAs: "9mm-147",
    weightGr: 147,
    diameterIn: 0.355,
    bc: 0.203,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_147, [[4, 1000]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,000 fps, 4 in test barrel); other lengths follow the Ballistics by the Inch 147 gr curve. Factory ratings often run fast, so a chronograph value is better. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Federal AE9FP", url: "https://www.federalpremium.com/handgun/american-eagle/american-eagle-handgun/11-AE9FP.html" },
    ],
  },
  {
    id: "win-9-usa-115",
    group: G9,
    brand: "Winchester",
    name: "Winchester USA 115 gr FMJ",
    sku: ["Q4172", "USA9W", "USA9MMVP"],
    short: "9mm Win USA 115",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.145,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[4, 1190]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,190 fps, 4 in test barrel, assumed); other lengths follow the Ballistics by the Inch 115 gr curve. Factory ratings often run fast, so a chronograph value is better.",
    sources: [{ label: "Winchester Q4172", url: "https://winchester.com/Products/Ammunition/Handgun/USA/Q4172" }],
  },
  {
    id: "rem-9-umc-115",
    group: G9,
    brand: "Remington",
    name: "Remington UMC 115 gr FMJ",
    sku: ["L9MM3", "23728", "L9MM3B", "23765", "L9MM3A", "23777"],
    short: "9mm UMC 115 FMJ",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.155,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[4, 1145]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,145 fps, 4 in test barrel); other lengths follow the Ballistics by the Inch 115 gr curve. Factory ratings often run fast, so a chronograph value is better.",
    sources: [{ label: "Remington L9MM3", url: "https://www.remington.com/handgun/umc-handgun/29-23728.html" }],
  },
  {
    id: "magtech-9a",
    group: G9,
    brand: "Magtech",
    name: "Magtech 115 gr FMJ",
    sku: ["9A", "MP9A"],
    short: "9mm Magtech 115 FMJ",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.144,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[4, 1135]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,135 fps, 4 in test barrel); other lengths follow the Ballistics by the Inch 115 gr curve. Factory ratings often run fast, so a chronograph value is better.",
    sources: [{ label: "Magtech 9A", url: "https://magtechammunition.com/products/ammunition/9mm-luger-115gr-fmj-2/" }],
  },
  {
    id: "sb-9-115",
    group: G9,
    brand: "Sellier & Bellot",
    name: "Sellier & Bellot 115 gr FMJ",
    sku: ["SB9A"],
    short: "9mm S&B 115 FMJ",
    sameAs: "9mm-115",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.116,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[6, 1280]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,280 fps, 6 in test barrel); other lengths follow the Ballistics by the Inch 115 gr curve. Factory ratings often run fast, so a chronograph value is better.",
    sources: [
      { label: "Sellier & Bellot SB9A", url: "https://www.sellierbellot.us/products/pistol-and-revolver-ammunition/pistol-and-revolver-cartridges/" },
    ],
  },
  {
    id: "pmc-9g",
    group: G9,
    brand: "PMC",
    name: "PMC Bronze 124 gr FMJ",
    sku: ["9G"],
    short: "9mm PMC 124 FMJ",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.143,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.7, 1063], [4.5, 1090], [16, 1215]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 3.7, 4.5 and 16 in (Pew Pew Tactical); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,110 fps (test barrel not stated). The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "PMC 9G", url: "https://pmcammo.com/product/bronze-9g/" },
    ],
  },
  {
    id: "speer-lawman-9-124",
    group: G9,
    brand: "Speer",
    name: "Speer Lawman 124 gr TMJ",
    sku: ["53651"],
    short: "9mm Lawman 124 TMJ",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.159,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.39, 1010], [4, 1085], [5.3, 1103]]),
    platform: "ar15",
    confidence: "low",
    notes: "Measured at 3.39, 4 and 5.3 in (AmmoLand); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,090 fps from a 4 in test barrel. Only pistol barrels were measured, so carbine velocities are less certain.",
    sources: [
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "Speer 53651", url: "https://www.speer.com/ammunition/lawman/lawman-handgun-training/19-53651.html" },
    ],
  },
  {
    id: "fed-hst-9-124",
    group: G9,
    brand: "Federal",
    name: "Federal HST 124 gr JHP",
    sku: ["P9HST1S"],
    short: "9mm HST 124",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.152,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.39, 1138], [3.5, 1135], [3.7, 1173], [4, 1200], [4.5, 1211], [4.7, 1158], [5.3, 1264], [12.5, 1289], [16, 1383], [16.1, 1256]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 10 barrel lengths from 3.39 to 16.1 in (LuckyGunner, Pew Pew Tactical, AmmoLand); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,150 fps from a 4 in test barrel. Readings at 16 in disagree by about 130 fps between carbines. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "LuckyGunner: defensive ammo in pistol-caliber carbines (2019)", url: "https://www.luckygunner.com/lounge/self-defense-ammo-for-pistol-caliber-carbines/" },
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "Federal P9HST1S", url: "https://www.federalpremium.com/handgun/personal-defense-hst/11-P9HST1S.html" },
    ],
  },
  {
    id: "fed-hst-9-147",
    group: G9,
    brand: "Federal",
    name: "Federal HST 147 gr JHP",
    sku: ["P9HST2S"],
    short: "9mm HST 147",
    sameAs: "9mm-147",
    weightGr: 147,
    diameterIn: 0.355,
    bc: 0.203,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_147, [[3.5, 973], [4.7, 995], [12.5, 1018], [16.1, 984]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 3.5, 4.7, 12.5 and 16.1 in (LuckyGunner); other lengths follow the Ballistics by the Inch 147 gr curve. Maker's rating: 1,000 fps from a 4 in test barrel. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "LuckyGunner: defensive ammo in pistol-caliber carbines (2019)", url: "https://www.luckygunner.com/lounge/self-defense-ammo-for-pistol-caliber-carbines/" },
      { label: "Federal P9HST2S", url: "https://www.federalpremium.com/handgun/personal-defense-hst/11-P9HST2S.html" },
    ],
  },
  {
    id: "speer-gd-9-124",
    group: G9,
    brand: "Speer",
    name: "Speer Gold Dot 124 gr JHP",
    sku: ["23618GD", "53618"],
    short: "9mm Gold Dot 124",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.134,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.5, 1067], [4.7, 1201], [12.5, 1341], [16.1, 1346]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 3.5, 4.7, 12.5 and 16.1 in (LuckyGunner); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,150 fps from a 4 in test barrel.",
    sources: [
      { label: "LuckyGunner: defensive ammo in pistol-caliber carbines (2019)", url: "https://www.luckygunner.com/lounge/self-defense-ammo-for-pistol-caliber-carbines/" },
      { label: "Speer 23618GD", url: "https://www.speer.com/ammunition/gold-dot/gold-dot-handgun-personal-protection/19-23618GD.html" },
    ],
  },
  {
    id: "speer-gd-9-124-plusp",
    group: G9,
    brand: "Speer",
    name: "Speer Gold Dot 124 gr JHP +P",
    sku: ["23617GD", "53617GD", "53617"],
    short: "9mm Gold Dot 124 +P",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.134,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.39, 1198], [3.5, 1141], [3.7, 1207], [4.02, 1222], [4.49, 1258], [4.5, 1281], [4.7, 1253], [12.5, 1401], [16, 1305], [16, 1458], [16.1, 1422]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 10 barrel lengths from 3.39 to 16.1 in (LuckyGunner, Pew Pew Tactical, Gun Tests); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,220 fps from a 4 in test barrel. Readings at 16 in range from 1,305 to 1,458 fps between carbines.",
    sources: [
      { label: "LuckyGunner: defensive ammo in pistol-caliber carbines (2019)", url: "https://www.luckygunner.com/lounge/self-defense-ammo-for-pistol-caliber-carbines/" },
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "Gun Tests: 9mm barrel lengths compared (2020)", url: "https://www.gun-tests.com/ammo/9mm-barrel-lengths-compared-in-range-performance-testing/" },
      { label: "Speer 23617GD", url: "https://www.speer.com/ammunition/gold-dot/gold-dot-handgun-personal-protection/19-53617GD.html" },
    ],
  },
  {
    id: "speer-gd-9-147",
    group: G9,
    brand: "Speer",
    name: "Speer Gold Dot 147 gr JHP",
    sku: ["23619GD", "53619"],
    short: "9mm Gold Dot 147",
    sameAs: "9mm-147",
    weightGr: 147,
    diameterIn: 0.355,
    bc: 0.164,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_147, [[3.39, 911], [4.02, 955], [4.49, 951], [16, 1080]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 3.39, 4.02, 4.49 and 16 in (Gun Tests); other lengths follow the Ballistics by the Inch 147 gr curve. Maker's rating: 985 fps from a 4 in test barrel.",
    sources: [
      { label: "Gun Tests: 9mm barrel lengths compared (2020)", url: "https://www.gun-tests.com/ammo/9mm-barrel-lengths-compared-in-range-performance-testing/" },
      { label: "Speer 23619GD", url: "https://www.speer.com/ammunition/gold-dot/gold-dot-handgun-personal-protection/19-23619GD.html" },
    ],
  },
  {
    id: "hdy-9-115-critical-defense",
    group: G9,
    brand: "Hornady",
    name: "Hornady Critical Defense 115 gr FTX",
    sku: ["90250"],
    short: "9mm Hornady 115 FTX",
    weightGr: 115,
    diameterIn: 0.355,
    bc: 0.129,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_115, [[3.39, 1091], [3.7, 1159], [4, 1135], [4.5, 1160], [5.3, 1193], [16, 1375]]),
    platform: "ar15",
    confidence: "medium",
    notes: "Measured at 6 barrel lengths from 3.39 to 16 in (Pew Pew Tactical, AmmoLand); other lengths follow the Ballistics by the Inch 115 gr curve. Maker's rating: 1,140 fps from a 4 in test barrel.",
    sources: [
      { label: "Pew Pew Tactical: 9mm ammo test (pistols and 16 in carbine)", url: "https://www.pewpewtactical.com/best-9mm-ammo-self-defense-range/" },
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "Hornady 90250", url: "https://www.hornady.com/ammunition/handgun/9mm-luger-115-gr-ftx-critical-defense" },
    ],
  },
  {
    id: "hdy-9-135-critical-duty",
    group: G9,
    brand: "Hornady",
    name: "Hornady Critical Duty 135 gr FlexLock +P",
    sku: ["90226"],
    short: "9mm Hornady 135 +P",
    weightGr: 135,
    diameterIn: 0.355,
    bc: 0.195,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[3.39, 1066], [4, 1110], [5.3, 1169]]),
    platform: "ar15",
    confidence: "low",
    notes: "Measured at 3.39, 4 and 5.3 in (AmmoLand); other lengths follow the Ballistics by the Inch 124 gr curve. Maker's rating: 1,110 fps from a 4 in test barrel. Only pistol barrels were measured, so carbine velocities are less certain.",
    sources: [
      { label: "AmmoLand: 9mm velocity by pistol (3.4 to 5.3 in)", url: "https://www.scribd.com/document/342823084/9x19-Data-Spreadsheet" },
      { label: "Hornady 90226", url: "https://www.hornady.com/ammunition/handgun/9mm-luger-p-135-gr-flexlock-critical-duty" },
    ],
  },
  {
    id: "sig-9-124-v-crown",
    group: G9,
    brand: "Sig Sauer",
    name: "Sig Sauer Elite V-Crown 124 gr JHP",
    sku: ["E9MMA2-50"],
    short: "9mm Sig 124 V-Crown",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.145,
    dragModel: "G1",
    mvByBarrel: fitCurve(BBTI_124, [[4, 1165]]),
    platform: "ar15",
    confidence: "low",
    notes: "From the maker's rating (1,165 fps, 4 in test barrel); other lengths follow the Ballistics by the Inch 124 gr curve. Factory ratings often run fast, so a chronograph value is better. Sig publishes no BC; 0.145 is typical of 124 gr JHPs.",
    sources: [
      { label: "Sig Sauer E9MMA2-50", url: "https://www.sigsauer.com/9mm-124gr-elite-v-crown-jhp-50-count.html" },
    ],
  },
  {
    id: "fed-hydra-shok-9-124",
    group: G9,
    brand: "Federal",
    name: "Federal Hydra-Shok 124 gr JHP",
    sku: ["P9HS1"],
    short: "9mm Hydra-Shok 124",
    sameAs: "9mm-124",
    weightGr: 124,
    diameterIn: 0.355,
    bc: 0.152,
    dragModel: "G1",
    mvByBarrel: BBTI_124,
    platform: "ar15",
    confidence: "high",
    notes: "Measured by Ballistics by the Inch in one barrel, cut down an inch at a time. Maker's rating: 1,120 fps from a 4 in test barrel. BBTI tested 2008 lots. The maker publishes no BC; this one is fitted to its downrange velocity table.",
    sources: [
      { label: "Federal P9HS1", url: "https://www.federalpremium.com/handgun/personal-defense-hydra-shok/11-P9HS1.html" },
      BBTI_9,
    ],
  },
];
